### PR TITLE
Basic Rover Movement

### PR DESCRIPTION
**Pull request by Cwighty**
Tests were interesting since the initial player location is random. 

I didn't test the api endpoint all the way yet, It looks like starting the game is in progress, so I didn't want to conflict with that.

Any feedback is welcome.

### CODE REVIEW

**Comment by snow-jallen** [comment]
What's the latest on this?  Is this ready to review?

**Comment by Cwighty** [comment]
> What's the latest on this? Is this ready to review?
I haven't added anything else to this. It should be good.

**Comment by Cwighty** [comment]
It looks like in the game controller the game got renamed to gameManager.Game, I got it working really quick. Is there a quick way to add a commit to this pull request?

**Comment by Cwighty** [comment]
Ready

**Comment by snow-jallen** [comment]
I don't know why I never saw any notification of your comments on this PR, I'm so sorry to be silent for so long. :(

**Comment by snow-jallen** [comment]
I read through your code, the movement logic is pretty different than I have it coded up now, you don't actually _move_ right or left, you just turn right or left so you can then go forward or backward.  Do you want to adjust your tests accordingly and we can work toward merging this in or do you want to just close the PR?

**Pull request closed without merging**
